### PR TITLE
Add StreamPad compatibility using the current codebase

### PR DESCRIPTION
**Pull request by LauraRozier**

### CODE REVIEW

**Comment by yewnyx** [comment]
Who/what is Grab Labs?

**Comment by LauraRozier** [comment]
https://github.com/grablabs/external_SubLink
They forked it to make their Twitch app..extension..w/e Twitch calls them work with OSC.
It was giving CGE a bunch of grief earlier today like weird / corrupted parameter names etc. To be able to properly debug it and having it run the current codebase I ported it back to the current source.

**Comment by yewnyx** [comment]
I'm cool with adding an Acknowledgements.md listing major contributions, and including them in it. It's great to welcome contributions.

For adding their name to startup specifically, I'd want them to engage here or on the discord directly, to be the one making the pull request adding their name, and to show involvement over time. It's fine for a text file to grow large, the startup text is specifically to prominently highlight core contributors like us and CGE.

Alternatively, could switch from the huge figgle fonts to just normal text acknowledgements, and that'd be OK too.

**Comment by LauraRozier** [comment]
Fair enough, uno momento

**Pull request merged**
